#!/bin/bash

PORT=4001
ENTRYPOINT="server/index.php"

export ISSUER=http://nym.dupunkto.org:$PORT
export ENCRYPTION_KEY=69420wowpenis

# Configure the PHP server to start two
# concurrent threads.
export PHP_CLI_SERVER_WORKERS=2

serve() {
  php -S 0.0.0.0:$PORT $ENTRYPOINT
}

deploy() {
  lift deploy nym
}

publish() {
  (cd client && mix docs)
  lift deploy docs
}

release() {
  (cd client && mix hex.publish)
}

generate() {
  export PASSPHRASE=$1

  php -r '
  $passphrase = getenv("PASSPHRASE");
  echo password_hash($passphrase, PASSWORD_DEFAULT) . "\n";
  '
}
