#!/bin/bash

PORT=4001
ENTRYPOINT="server/index.php"

export IDENTITY=https://dupunkto.org
export ISSUER=http://nym.dupunkto.org:$PORT
export ENCRYPTION_KEY=69420wowpenis

# Configure the PHP server to start two
# concurrent threads.
export PHP_CLI_SERVER_WORKERS=2

serve() {
  php -S 0.0.0.0:$PORT $ENTRYPOINT
}

generate() {
  export PASSPHRASE=$1

  php -r '
  $passphrase = getenv("PASSPHRASE");
  echo password_hash($passphrase, PASSWORD_DEFAULT) . "\n";
  '
}